### ISSUE TITLE
第1階段-設計每個頁面的Mock

### ISSUE THREAD

**Issue by ben196888** [FuBoTeam/fubo-flea-market#10]
# Write A Detailed Mock of the Screen

我是參考這篇一步一步規劃的 [step-by-step-guide-to-building-react-redux-apps-using-mocks](https://medium.com/@rajaraodv/step-by-step-guide-to-building-react-redux-apps-using-mocks-48ca0f47f9a#.br9ibrhjq)
## Definition of Done

明天補XD
## Todo list
- [ ] Write A Detailed Mock of the Screen
- [ ]  Divide The App Into Components
- [ ] List State and Actions For Each Component

先做到這樣就好，第四步開始就會是滿滿的實作了。
